- repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

- repo: local
  # prospector: collection of linters
  - id: prospector
    language: system
    types: [file, python]
    name: prospector
    description: "This hook runs Prospector: https://github.com/landscapeio/prospector"
    entry: prospector


